Repository port-labs/port-docs, pull requests merged in 2024-12, with the labels that each got.

#1765 PORT-10735 DataDog integration documentation refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/datadog.md
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/examples.md
Labels: enhancement

#1784 PORT-11585 Octopus Deploy Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md
Labels: enhancement

#1785 PORT-11586 New Relic Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md
Labels: documentation

#1792 PORT-11587 Sentry Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md
Labels: documentation

#1798 PORT-11591 Statuspage Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage/_category_.json
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage/_statuspage_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage/examples.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage/statuspage.md
Labels: documentation

#1814 PORT-11596 Kubecost Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost/kubecost.md
Labels: documentation

#1799 PORT-11592 Snyk Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
Labels: documentation

#1789 PORT-11635 Bug | Fix Mapping Configuration in New Relic Cloud Ingesting
  docs/guides/all/ingest-cloud-resources-using-newrelic.md
Labels: bug

#1815 PORT-11597 OpenCost Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost/kubecost.md
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
Labels: documentation

#1816 PORT-11598 Kafka Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka.md
Labels: documentation

#1817 PORT-11599 Backstage Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/other/backstage.md
Labels: documentation

#1783 PORT-11584 Jenkins Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/cicd/jenkins/jenkins.md
Labels: enhancement

#1797 PORT-11590 ServiceNow Integration guide refactoring
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/servicenow.md
Labels: documentation

#1820 PORT-11785 Github App installation guide refactoring
  docs/actions-and-automations/setup-backend/github-workflow/github-workflow.md
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/aws-exporter/examples/examples.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_supported_resources.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/git/github/advanced.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/github/gitops/gitops.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/github/installation.md
  docs/customize-pages-dashboards-and-plugins/page/dashboard-page.md
  docs/guides/all/automate-slack-alert-for-overdue-prs.md
  docs/guides/all/connect-github-codeowners-with-service-team-and-user.md
  docs/guides/all/connect-github-pr-with-jira-issue.md
  docs/guides/all/connect-github-pr-with-sonar-analysis.md
  docs/guides/all/connect-github-repository-with-launchdarkly-project.md
  docs/guides/all/connect-github-repository-with-sonarqube-project.md
  docs/guides/all/eks-as-a-service-action.md
  docs/guides/all/ingest-checkmarx-kics-scan-into-your-catalog.md
  docs/guides/all/ingest-dependencies-from-package-json-to-service.md
  docs/guides/all/ingest-javascript-packages-into-your-catalog.md
  docs/guides/all/ingest-security-issues-from-sarif-files-to-services.md
  docs/guides/all/ingest-software-bill-of-materials-sbom-into-your-catalog.md
  docs/guides/all/ingest-swagger-paths-into-your-catalog.md
  docs/guides/all/ingest-trivy-vulnerabilities-into-your-catalog.md
Labels: documentation

#1854 PORT-11708 Bug | Deprecate the old metrics guide
  docs/guides/all/pull-request-metrics.md
Labels: documentation

#1857 PORT-9739 Update Catalogue Page
  docs/customize-pages-dashboards-and-plugins/page/catalog-page.md
  static/img/software-catalog/pages/EditPageForm.png
  static/img/software-catalog/pages/MyTeamsFilter.png
  static/img/software-catalog/pages/PageMenu.png
  static/img/software-catalog/pages/TableFilterMenu.png
  static/img/software-catalog/pages/TableOperationsBar.png
  static/img/software-catalog/pages/TableSearchBar.png
  static/img/software-catalog/pages/TableSortMenu.png
  static/img/software-catalog/pages/catalogPageDescriptionForm.png
  static/img/software-catalog/pages/excludePropertiesForm.png
  static/img/software-catalog/pages/initialFiltersForm.png
  static/img/software-catalog/pages/meFilter.png
Labels: documentation

#1846 PORT-11797 Created Lets test it section for all the integration guides that do not have it
  docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/azure-devops.md
Labels: documentation

#1868 PORT-12046 Fix indentations
  docs/build-your-software-catalog/custom-integration/iac/terraform/terraform.md
Labels: documentation
