Repository port-labs/port-docs, pull requests merged in 2025-06, with the labels that each got.

#2382 PORT-14793 Bug | To mention that Port Automations will not trigger upon deleting related entities
  docs/actions-and-automations/define-automations/setup-trigger.md
Labels: bug

#2394 Portn 2674 add metrics collection instructions to integration docs
  docs/api-reference/get-an-integrations-metrics-and-sync-status.api.mdx
  docs/api-reference/sidebar.ts
  docs/build-your-software-catalog/sync-data-to-catalog/ai-agents/github-copilot/github-copilot.md
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/datadog.md
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/dynatrace.md
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md
  docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
  docs/build-your-software-catalog/sync-data-to-catalog/cicd/jenkins/jenkins.md
  docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost/kubecost.md
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/aws.md
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/azure.md
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/gcp.md
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/sonarqube.md
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
  docs/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka.md
  docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/launchdarkly.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/azure-devops.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket-cloud/bitbucket-cloud.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/GitLab-v2.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/gitlab.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie/opsgenie.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/pagerduty.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage/statuspage.md
  docs/build-your-software-catalog/sync-data-to-catalog/kubernetes-stack/komodor.md
  docs/build-your-software-catalog/sync-data-to-catalog/kubernetes-stack/kubernetes/kubernetes.md
  docs/build-your-software-catalog/sync-data-to-catalog/other/amplication.md
  docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md
  docs/build-your-software-catalog/sync-data-to-catalog/project-management/linear/linear.md
  docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md
  docs/build-your-software-catalog/sync-data-to-catalog/templates/_metrics_and_sync_status.mdx
  static/apispec.yaml
  static/rawApiSpec.yaml
Labels: waiting for prod

#2418 PORTN-2656 Manage and visualize your LaunchDarkly feature flags
  docs/guides/all/_toggle-launchdarkly-feature-flag.md
  docs/guides/all/manage-and-visualize-your-launchdarkly-feature-flags.md
  src/components/guides-section/consts.js
  static/img/guides/launchDarklyDashboard1.png
  static/img/guides/launchDarklyDashboard2.png
Labels: documentation

#2419 PORTN-2656 Add new guide for managing and visualizing PagerDuty incidents
  docs/guides/all/manage-and-visualize-pagerduty-incidents.md
  src/components/guides-section/consts.js
  static/img/guides/pagerDutyDashboard1.png
  static/img/guides/pagerDutyDashboard2.png
Labels: documentation

#2478 Bug | PORT-15063 Explain at the beginning what the benefit is of doing it directly from Port, rather than from PagerDuty
  docs/guides/all/create-pagerduty-incident-from-newrelic-alert.md
Labels: bug
