Repository port-labs/port-docs, pull requests merged in 2025-09, with the labels that each got.

#2752 Added the suggested changes to the sctructure table.
  archive/complete-use-cases/_iac-templates.md
  docs/actions-and-automations/create-self-service-experiences/setup-ui-for-action/setup-ui-for-action.md
  docs/actions-and-automations/setup-backend/webhook/examples/terraform-no-code-resource-provisioning.md
  docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/setup-blueprint.md
  docs/guides/all/create-cloud-resource-using-iac.md
  docs/guides/all/let-developers-enrich-services-using-gitops.md
  docs/guides/all/scaffold-a-new-service.md
  docs/guides/all/setup-slack-reminders.md
  docs/scorecards/overview.md
  docs/solutions/resource-self-service/setup-approval-workflows.md
Labels: bug

#2709 PORT-1483 Enhance incident management guide to automate Slack channel and GitHub
  docs/guides/all/create-slack-channel-for-reported-incident.md
  src/components/guides-section/consts.js
Labels: bug

#2742 Bug PORT-12434 Add caution note regarding service account limitations for Ocean integrations
  docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md
Labels: bug

#2804 change the default mapping of gitlab-v2 to gitlabRepository from service
  docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/GitLab-v2.md
Labels: bug

#2803 Port 15353 bug add more details on v 2 version parameter on some action endpoints
  docs/api-reference/approve-an-action-run.api.mdx
  docs/api-reference/get-actions-automations.api.mdx
  docs/api-reference/get-all-action-runs.api.mdx
  docs/api-reference/get-an-action-runs-details.api.mdx
  docs/api-reference/update-an-action-run.api.mdx
  static/apispec.yaml
Labels: bug

#2797 Portn 3660 add organization announcement banner feature
  docs/customization.md
Labels: waiting for prod

#2814 Added the github issue mapping configuration to the trigger copilot guide
  docs/guides/all/trigger-github-copilot-from-port.md
Labels: bug

#2782 Find internal documentation with AI Guide
  docs/guides/all/find-internal-documentation-with-ai.md
  src/components/guides-section/consts.js
  static/img/guides/internal-docs-ai-context-1.png
  static/img/guides/port-ai-assistant-interface.png
Labels: Ready for final review

#2830 Add auto-assign feature for GitHub Copilot in issue creation
  docs/guides/all/trigger-github-copilot-from-port.md
Labels: bug

#2826 Bug Track AI Driven PR's
  docs/guides/all/track-ai-driven-pull-requests.md
Labels: bug, waiting for prod

#2828 Add track ai driven guide link to prerequisite in self healing scorcard guide
  docs/guides/all/self-heal-scorecards-with-ai.md
Labels: bug

#2802 Change real-time to self-hosted and scheduled to ci
  docs/build-your-software-catalog/sync-data-to-catalog/ai-agents/github-copilot/_github_copilot_one_time_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/ai-agents/github-copilot/github-copilot.md
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/_datadog_one_time_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/datadog.md
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/dynatrace.md
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md
  docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md
  docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
  docs/build-your-software-catalog/sync-data-to-catalog/cicd/jenkins/jenkins.md
  docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost/kubecost.md
  docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/aikido/aikido.md
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/sonarqube.md
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md
  docs/build-your-software-catalog/sync-data-to-catalog/event-processing/_kafka_one_time_docker_params.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka.md
  docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/launchdarkly.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/_azuredevops_one_time_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/installation.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-cloud/_bitbucket_cloud_one_time_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-cloud/installation.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-server/_resources/_bitbucket_cloud_one_time_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-server/_templates/_ocean_saas_installation.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-server/bitbucket-server.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/github-ocean/_github_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/git/github-ocean/installation/_install_methods.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/_gitlab_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/installation.md
  docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_one_time_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie/opsgenie.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/pagerduty.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/servicenow.md
  docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage/statuspage.md
  docs/build-your-software-catalog/sync-data-to-catalog/kubernetes-stack/komodor.md
  docs/build-your-software-catalog/sync-data-to-catalog/other/amplication.md
  docs/build-your-software-catalog/sync-data-to-catalog/other/backstage.md
  docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira-server/jira-server.md
  docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/_jira_one_time_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md
  docs/build-your-software-catalog/sync-data-to-catalog/project-management/linear/_linear_one_time_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/project-management/linear/linear.md
  docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md
  docs/build-your-software-catalog/sync-data-to-catalog/templates/_ocean_saas_installation.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/terraform-cloud/terraform-cloud.md
  docs/generalTemplates/_integration_template.md
Labels: waiting for prod

#2827 Added the 8 new routes to the AI folder of the API
  docs/api-reference/change-a-specific-provider-configuration.api.mdx
  docs/api-reference/change-default-llm-provider-and-model.api.mdx
  docs/api-reference/create-or-connect-an-llm-provider.api.mdx
  docs/api-reference/delete-a-specific-provider-configuration.api.mdx
  docs/api-reference/get-a-specific-provider-configuration.api.mdx
  docs/api-reference/get-an-integrations-metrics-and-sync-status.api.mdx
  docs/api-reference/get-configured-llm-providers.api.mdx
  docs/api-reference/get-default-llm-provider-and-model.api.mdx
  docs/api-reference/get-monthly-ai-invocations-quota-usage.api.mdx
  docs/api-reference/sidebar.ts
  static/apispec.yaml
Labels: waiting for prod

#2719 [Docs] Add Checkmarx Integration Documentation
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/_category_.json
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/_checkmarx_docker_parameters.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/checkmarx.md
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/_category_.json
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-api-security/_checkmarx_exporter_example_api_security_blueprint.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-api-security/_checkmarx_exporter_example_api_security_port_app_config.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-container-security/_checkmarx_exporter_example_container_security_blueprint.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-container-security/_checkmarx_exporter_example_container_security_port_app_config.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-kics/_checkmarx_exporter_example_kics_blueprint.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-kics/_checkmarx_exporter_example_kics_port_app_config.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-project-scan/_checkmarx_exporter_example_project_blueprint.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-project-scan/_checkmarx_exporter_example_project_scan_port_app_config.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-project-scan/_checkmarx_exporter_example_scan_blueprint.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-project/_checkmarx_exporter_example_project_blueprint.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-project/_checkmarx_exporter_example_project_port_app_config.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-sast/_checkmarx_exporter_example_sast_blueprint.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-sast/_checkmarx_exporter_example_sast_port_app_config.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-sca/_checkmarx_exporter_example_sca_blueprint.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-sca/_checkmarx_exporter_example_sca_port_app_config.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-scan/_checkmarx_exporter_example_scan_blueprint.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/example-scan/_checkmarx_exporter_example_scan_port_app_config.mdx
  docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/checkmarx/examples/examples.md
  src/components/ocean-saas-specifics/live-events.jsx
Labels: Ready for final review
